/**********************************************************************
 * Extern for alertify
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var alertify = {
    "alert": function () {},
    "confirm": function () {},
    "extend": function () {},
    "init": function () {},
    "log": function () {},
    "prompt": function () {},
    "success": function () {},
    "error": function () {},
    "set": function () {},
    "labels": {
        "ok": {},
        "cancel": {}
    }
};
/**********************************************************************
 * End Generated Extern for alertify
   /**********************************************************************/
